CREATE TABLE `food_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`keywords` text DEFAULT '[]' NOT NULL,
	`is_branded` integer DEFAULT 0 NOT NULL,
	`brand` text,
	`is_packaged` integer DEFAULT 0 NOT NULL,
	`ingredients` text,
	`review_status` text DEFAULT 'pending' NOT NULL,
	`source` text DEFAULT 'ai_estimated' NOT NULL,
	`calories_per_100g` real DEFAULT 0 NOT NULL,
	`protein_g` real DEFAULT 0 NOT NULL,
	`carb_g` real DEFAULT 0 NOT NULL,
	`fat_g` real DEFAULT 0 NOT NULL,
	`fiber_g` real,
	`sugar_g` real,
	`sodium_mg` real,
	`saturated_fat_g` real,
	`cholesterol_mg` real,
	`trans_fat_g` real,
	`potassium_mg` real,
	`vitamin_a_mcg` real,
	`vitamin_c_mg` real,
	`vitamin_d_mcg` real,
	`vitamin_b12_mcg` real,
	`calcium_mg` real,
	`iron_mg` real,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL
);
